### ISSUE TITLE
primer3 2.3.7 hangs but not 2.4.0

### ISSUE THREAD

**Issue by nh13** [primer3-org/primer3#10]
Input: 

```
SEQUENCE_PRIMER_REVCOMP=CTCTACCTATAAATCTTCCCACTA
SEQUENCE_PRIMER=GGAAAGATGAAAAATTATAACCAAGCATAATAT
PRIMER_EXPLAIN_FLAG=1
PRIMER_FIRST_BASE_INDEX=1
PRIMER_PICK_INTERNAL_OLIGO=0
PRIMER_PICK_LEFT_PRIMER=1
PRIMER_PICK_RIGHT_PRIMER=1
PRIMER_MIN_SIZE=18
PRIMER_MAX_SIZE=34
PRIMER_MIN_TM=54.0
PRIMER_TASK=check_primers
PRIMER_THERMODYNAMIC_PARAMETERS_PATH=/path/to/primer3-2.3.7/src/primer3_config/
=
```

Running `primer3_core < in` hangs in v2.3.7 but not 2.4.0.  Since 2.4.0 is a release, I have also submitted a PR to `primer3`'s bioconda recipe: https://github.com/bioconda/bioconda-recipes/pull/10122

**Comment by untergasser** [comment]
Hi,
I tested your input with this version:
https://github.com/primer3-org/primer3/commit/2faf322c025772d21dbf0cc7798a89c2c89919bd
on Ubuntu 18.04. It worked without problem.
Best,
Andreas
The output:
uni@ubuntu:~/embl/y_primer3/src$ ./primer3_core < in
SEQUENCE_PRIMER_REVCOMP=CTCTACCTATAAATCTTCCCACTA
SEQUENCE_PRIMER=GGAAAGATGAAAAATTATAACCAAGCATAATAT
PRIMER_EXPLAIN_FLAG=1
PRIMER_FIRST_BASE_INDEX=1
PRIMER_PICK_INTERNAL_OLIGO=0
PRIMER_PICK_LEFT_PRIMER=1
PRIMER_PICK_RIGHT_PRIMER=1
PRIMER_MIN_SIZE=18
PRIMER_MAX_SIZE=34
PRIMER_MIN_TM=54.0
PRIMER_TASK=check_primers
PRIMER_THERMODYNAMIC_PARAMETERS_PATH=/home/uni/primer3/src/primer3_config/
PRIMER_LEFT_EXPLAIN=considered 1, ok 1
PRIMER_RIGHT_EXPLAIN=considered 1, ok 1
PRIMER_PAIR_EXPLAIN=considered 1, ok 1
PRIMER_LEFT_NUM_RETURNED=1
PRIMER_RIGHT_NUM_RETURNED=1
PRIMER_INTERNAL_NUM_RETURNED=0
PRIMER_PAIR_NUM_RETURNED=1
PRIMER_PAIR_0_PENALTY=23.983703
PRIMER_LEFT_0_PENALTY=14.400678
PRIMER_RIGHT_0_PENALTY=9.583025
PRIMER_LEFT_0_SEQUENCE=GGAAAGATGAAAAATTATAACCAAGCATAATAT
PRIMER_RIGHT_0_SEQUENCE=CTCTACCTATAAATCTTCCCACTA
PRIMER_LEFT_0=1,33
PRIMER_RIGHT_0=200,24
PRIMER_LEFT_0_TM=58.599
PRIMER_RIGHT_0_TM=54.417
PRIMER_LEFT_0_GC_PERCENT=24.242
PRIMER_RIGHT_0_GC_PERCENT=37.500
PRIMER_LEFT_0_SELF_ANY_TH=0.00
PRIMER_RIGHT_0_SELF_ANY_TH=0.00
PRIMER_LEFT_0_SELF_END_TH=0.00
PRIMER_RIGHT_0_SELF_END_TH=0.00
PRIMER_LEFT_0_HAIRPIN_TH=29.33
PRIMER_RIGHT_0_HAIRPIN_TH=0.00
PRIMER_LEFT_0_END_STABILITY=1.2800
PRIMER_RIGHT_0_END_STABILITY=2.7400
PRIMER_PAIR_0_COMPL_ANY_TH=0.00
PRIMER_PAIR_0_COMPL_END_TH=0.00
PRIMER_PAIR_0_PRODUCT_SIZE=200
=
