### ISSUE TITLE
Batching multiple sequences in ntthal

### ISSUE THREAD

**Issue by nh13** [primer3-org/primer3#12]
I was wondering the appetite for a PR where we could batch many sequences to run `ntthal`.  I want to perform 100K+ invocations of `ntthal`, and I'd rather just send `ntthal` a stream of data and have one `ntthal` process handle all the requests.  I am only modifying the sequences I pass in (`-s1` and `-s2`) so I see a few options:

1. If `-s1` and `-s2` are not defined, then `ntthal` reads in from standard input. 
2. A new argument (`-f`?) that specifies a file with input sequences to process.

Thanks for considering this idea!

**Comment by bioinfo-ut** [comment]
Thank you for the idea, but this enhancement is probably not our first priority.
This should be relatively easy to achieve with the help of a small bash or PERL script. With 100K primer pairs you have to post-process the output with the help of some script anyway.

**Comment by nh13** [comment]
Unfortunately, I do have a script and it still takes too long to run the utility 100K+ times.  My question was if you’d accept a PR (from me) not that you’d have to write it. My apologies if that wasn’t clear.

**Comment by bioinfo-ut** [comment]
Feel free to open pull request, if thats what you mean by PR. It was not clear indeed :-).
