### ISSUE TITLE
PRIMER_LOWERCASE_MASKING=1 has no effect

### ISSUE THREAD

**Issue by hil-elrick** [primer3-org/primer3#13]
As title says, even when lowercase masking is set in the settings file it has no affect on the primers returned. Many that are returned are entirely within a lowercase masked region. 

Edit: this only seems to happen in the command-line program (primer3-2.4.0). Using the same settings file for both the web and command-line version of primer3 returns different results. (The web version works correctly but the command-line version seems to ignore the PRIMER_LOWERCASE_MASKING flag)

**Comment by triinuk** [comment]
Please, provide us input file with input sequence and with flags. And give the Primer3 web-address that you used.

**Comment by hil-elrick** [comment]
http://primer3.ut.ee/ was the web address I used. First I entered settings on the web tool and downloaded them to [LOWERCASE_MASKING_SETTINGS.txt](https://github.com/primer3-org/primer3/files/2446595/LOWERCASE_MASKING_SETTINGS.txt). All the flags are default except for Lowercase Masking. I used this input: [TEST_SEQUENCE_INPUT.txt](https://github.com/primer3-org/primer3/files/2446495/TEST_SEQUENCE_INPUT.txt) for both web and command-line. In the web version I get the following result: [WEB_OUTPUT.txt](https://github.com/primer3-org/primer3/files/2446603/WEB_OUTPUT.txt) which seems to have had the LOWERCASE_MASKING flag successfully applied. The command line version though (run with the command 'primer3_core --p3_settings_file="LOWERCASE_MASKING_SETTINGS.txt" < "TEST_SEQUENCE_INPUT.txt"') gives the output: [COMMAND_LINE_OUTPUT.txt](https://github.com/primer3-org/primer3/files/2446605/COMMAND_LINE_OUTPUT.txt). The top primers don't match, and the command line version gives two primers that are entirely lowercase. I've confirmed that changing other flags in the command-line settings file changes the output, it seems to be only the LOWERCASE_MASKING that's being ignored.

**Comment by untergasser** [comment]
You are right, this is an issue. If PRIMER_MASK_TEMPLATE=0 was set, it overwrote the lowercase masking and set it also to 0. Of course, this is not how it should work. Thank you for reporting this. 

It was fixed in this commit:
https://github.com/primer3-org/primer3/commit/25a4ab22298a0195079e3a9c004c02a49d0262ff

Best,
Andreas
