### ISSUE TITLE
feature request: ability to specify left and right primer overhangs

### ISSUE THREAD

**Issue by scottbecker** [primer3-org/primer3#14]
Some pcr experiments required adding overhangs to primers, e.g. restriction sites or homology arms.  It would be nice to be able to tell primer3 about left and right primer overhangs that should be taken into account when doing hairpin and self-dimer scoring for the final primer.

**Comment by bioinfo-ut** [comment]
Good idea. Thanks for the suggestion.

**Comment by untergasser** [comment]
The overlap positions were added in https://github.com/primer3-org/primer3/commit/cbf451d1981adc1b9e35211f6fce45396c6e652a

It will be part of the next release.

Best,
Andreas
