### ISSUE TITLE
Final record not terminated by '=' value

### ISSUE THREAD

**Issue by DeondeJager** [primer3-org/primer3#16]
Hi guys,

I'm trying to run primer3 release 2.4.0 on Ubuntu 18.04 LTS using an input file generated by the program MSDB (Microsatellite Search and Building Database). But I get an error saying the final record is not terminated by an '=', but it is. See the output below (include the command I used). 

deon@deon-ubuntu:~/Software/primer3/src$

 ./primer3_core /home/deon/Documents/Microsatellite_Design/Tri/primer_design_TRI_short.txt 
SEQUENCE_ID=1
SEQUENCE_TEMPLATE=gccgccgagctaggcctggatcggtcggtctcggcaatcgccgagataaagaggaactcgcgaactttcgttgaaacaatgggaggggcttggctgaggctattagcccggttttgatgccaggcgttatcaagagttgaagccgagccttcaacatcaaccttctttcaggccgccatcttgattccccttgctcccatCCGCCGCCGCCGCCGCCGCCGacgacgccgccgacgacgactaagttttgtaagcttcgaggaagttcgtagaaggagccggcaagcaagcgctattacgtcaactcattattccggtcattttcaataagcgatagtctttcgttggcaacaggcatactgcggccgctcatcaaccatattattaattgctaatattaaaagtcctttcacgaatcctt
SEQUENCE_TARGET=201,21
PRIMER_MAX_END_STABILITY=250.0
PRIMER_PRODUCT_SIZE_RANGE=100-280
=
SEQUENCE_ID=2
SEQUENCE_TEMPLATE=aaatataattacttataatataattataaaaatacatttacttattaactatggaaattataaaattaatggaaattacttaatcaaatttattttcaatttttcaattttaatttataactttctaaacctaacaatagatacttttatattttatttactttcaccgcttttgtataaaaaaaaaacttactatgagcATAATAATAATAATAATAATAatggtattaacaataattacaaataataaaatttacagcagagtaatatgacattaatgttttgataataaagaccacattgttaaaaataaagaaaagctctccattgaatgaatacatatcaacgttattgtcgcatatgacaaaatagctttcatgctttcgagtaatatatttctatataatataattcaataagc
SEQUENCE_TARGET=201,21
PRIMER_MAX_END_STABILITY=250.0
PRIMER_PRODUCT_SIZE_RANGE=100-280
=
; Final record not terminated by '='value: 50.0alue: 250.0
=
; Final record not terminated by '='value: 50.0Y value: `250.0

**Comment by untergasser** [comment]
Hi,
this could be a newline windows vs linux issue. Could you send the input file so we could recreate the bug?
Best,
Andreas

**Comment by untergasser** [comment]
Hi,
maybe this commit fixing windows newlines solved your bug report:
https://github.com/primer3-org/primer3/commit/2faf322c025772d21dbf0cc7798a89c2c89919bd
Best,
Andreas

**Comment by untergasser** [comment]
Taking the input from above it run without errors in this version:
https://github.com/primer3-org/primer3/commit/f382935091e1e49bcf2ce8afe8d4d034776509a1
So without the input file I cannot investigate further.

Best,
Andreas

**Comment by untergasser** [comment]
Hi Deon,

it was the windows '\r\n' newline (in your file) vs Linux '\n' newline (what old Primer3 expected) issue. Now Primer3 an handle both, so this issue is fixed. Thanks for reporting!

Best,

Andreas

**Comment by 326reborn** [comment]
Hi Deon and Andreas,

I met the same problem as you in the Latest release. I'm sure my input file is the Linux '\n' newline by 'cat -A'. I got it by the misa.pl and p3_in.pl script which download from MISA.
Looking forward to your reply.

Best,

Yu zhang
![test1](https://user-images.githubusercontent.com/48210355/113802994-3da05500-978e-11eb-816c-71ec4cc6888a.png)
[test1.zip](https://github.com/primer3-org/primer3/files/6268621/test1.zip)

**Comment by untergasser** [comment]
Maybe your sequence is too big, try something up to 50000bp.

Best,
Andreas

**Comment by Adinivich** [comment]
Hi all! I have the same 'primer3_core: Input line with no '=': ' error, with the folling kind of input file:

SEQUENCE_ID=NC_014426.2_774682-775882
SEQUENCE_TEMPLATE=GGCAGATGTCACTCTTCGATACCTTTACGTTCGACGGTAAGTAATATTCGACTCGCGCGGGCAAGGCGCGATGTAACAGATTGTTTCGTTGTTTCTATGAATTACATCCGGCTCCTCTGTGAGGAAAACCAAGCCATCATCGCCTCCTGGCGAACGGGTTAGGAATCCTCCCCGTCCGCGTATCCCTGAGCATCTCCCCCGATCTCGCGTGCTTATCcatcaatcgcgcgcgcaaaaagtccaccgccgccgtcggaggctccgccgtctcgtctccgcgcgcgccctccaACGCGACCACCTCGAATCCATCCCGCTCGTACGTCCGCCGCTTCGCCTCCCGTCGCTCCCTCTTACTCCTCTTCACCCGTTTCTTCCCTCCGACGTGcgcctcgtacgcgtcgaacgcccgtcttttctcgccgccgcgccgtccgtccccgagcgcgcccgcgacgacgtcctccgGAAGCGCCTCGagatcgtcttcgtccgccctcgcgtcgtccgccgacgccgtccacgccgtcgtcgtcgccgtttCCGTCCCATcgtcccctcgcgcgcgcgcgttcgaacgcgccgccggtcgtcgcgtcttcgccgccgccgccgccgctcgcaccgccgcgcgcgcgttcgcccgcgcccgcgtcgcctccgcgcgtccgcgcgccccgctCACTTCCTCGGGCGCGTCCGAGTCCGAGcgttcgtcctcgcccgcgagcgccgcgcgcgtcgagcgcggcgctcgcgNNNNNNNNNNNNNNNNNNNNGGGGGGGGCGGCGgggcggacgaggacgacggcccGGTGAgaccgcggtcgaggacgagcgcggagacgtcgcgggTGCGGTGTGATGGATGTCGGTGCACGCTGGCGTAtccggcgggcgcggcggcggtgcggtgcgcggtgtgcgggacggtgacgcggtgcgagacgggcgcgggacgtttggacggcggacgcgcggacgacgcgagcgccgctcgaggtggtcccgcgacgacggcgctgaCGATGGAGAACATGGTGGTGGTGGAGAATCCGCCGACGTTGACGGTGGACGGACGAGTGGTGACGAACATCGCGGTCGGGGTGAAACTCGACGATTGACTCGAcggtcgcggacgaacgacgcgacggtcgcgacgccgacgacatTTAGAGTCGGACGTATCGGATTCAATTTT
SEQUENCE_TARGET=520,80
PRIMER_TASK=generic
PRIMER_PICK_LEFT_PRIMER=1
PRIMER_PICK_RIGHT_PRIMER=1
PRIMER_OPT_SIZE=18
PRIMER_MIN_SIZE=15
PRIMER_MAX_SIZE=25
PRIMER_PRODUCT_SIZE_RANGE=250-600
PRIMER_GC_CLAMP=1
PRIMER_MIN_TM=58
PRIMER_OPT_TM=62
PRIMER_MAX_TM=66
PRIMER_OPT_GC_PERCENT=60
=


SEQUENCE_ID=NC_014427.2_79636-80836
SEQUENCE_TEMPLATE=TTCCGACACTGTCCGACCGCCGGTTTCGGTACTGAGCCGTGTATGAAAACAACCCCTAATATCTCAAGGGAAACAACGTGAAATACAAGTGAAATGGAAAAAAGTGTGAAAAACGTGAATTGTCTTTGCGCGCGTGTAGCTGTAAGAGGTCCGATCGAAGTTCGTGTGTTTTGGACGTGAATTTCAGCGAAAATAATTATTTGATGTGCAGTGTCAACACGTCATCATGGCACATCAGCGCGCATTTCTAGGGGCGGGGGACTTGCGCAAGACACCCCGAAACTGCCGCAATTTGCATTGCACTTGCATCTTGCAGGTGCAAAATGCCCCCATATTCCAGAGTAGGTAGGAAGATGCCATTTGTCCGAACATTATAATTATACTGTTTACCCATATGATCACCCTTAAACCCTAAACTAAACCCTAATCCACACGATAAtttgacgccgccgcccctGAATCGCGTGTCGGAGCCCCTTAAAAAcacccgcgtgtgcgggcgCCCACCCCTAATCTCTTGCGCAAGACGCCCCAAAACACCTGCAATTTGCACCTGCAATTTTGCTCTTGCATCTTGCAGGTAAAATTTCCCCCACCCCTAGGGACGTACAATCATCCAGACGAAACGAATCGCCCGTGGTGTCGCTGCGCAttggcgcggcgcgtcgattgCGTTGcgtgcgccgacgtcgacgcgcctcggtcgcggcggcgccgtcgcctcggtcgcacgcgcgtcgatcgatcgtcgaacgtcgatcgatcgcgtcgcgcgatggaggacgagcgcgaggattacggtgacgacgtcgacgacgtcgtcgacgcgctcgaggcggcggaggacgaggatgaACGAGACCTCGAGGGgggggacgcggacggacgGGTGAtcgtcgagagcgacgagcgaggcgacgcgctcggtacGCACGGTCGAAGAGGAACCGGTGGGGCGGTACCGAGACACttgcgaacgacgacgccgtacATGACGAAGTACGAACGGGCGAGGGTTCtgggaacgcgcgcgttgcagATCTCGATGAATGCGCCGGTGCTCGTGCagctcgagggcgagacGGATCCGTTGGAGATCGCGGGGAAGGAGCTCCGGGAGAAGAGAGTGCCGTTCGTCGTTCGAAGATATCTCCCGGATGGCTCGTACGAGGATTGGTGCATCGAGGAGCTGATCGTGCAC
SEQUENCE_TARGET=520,80
PRIMER_TASK=generic
PRIMER_PICK_LEFT_PRIMER=1
PRIMER_PICK_RIGHT_PRIMER=1
PRIMER_OPT_SIZE=18
PRIMER_MIN_SIZE=15
PRIMER_MAX_SIZE=25
PRIMER_PRODUCT_SIZE_RANGE=250-600
PRIMER_GC_CLAMP=1
PRIMER_MIN_TM=58
PRIMER_OPT_TM=62
PRIMER_MAX_TM=66
PRIMER_OPT_GC_PERCENT=60
=

What should I change? Thanks!
