### ISSUE TITLE
Problem with Primer3 installation - bin folder not present

### ISSUE THREAD

**Issue by ogthomas** [primer3-org/primer3#19]
Hi, I am having trouble with the Primer3 installation instructions and am unable to get past instruction 2 from the Primer3 Release 2.3.7 Manual (http://primer3.sourceforge.net/primer3_manual.htm#installMac) for installation on Mac OSX. The manual gives the following instructions:

2. The binary files are located in the 'bin' [for 'binary'] folder

But there is no folder in the 2.3.7 download (from here http://primer3.sourceforge.net/releases.php) called "bin" and I am therefore unable to get past this point. I also tried downloading a different version of Primer3 directly from SourceForge (https://sourceforge.net/projects/primer3/) but have come up against the same problem.

I wondered if anyone else has encountered this problem, or if the instructions have not been updated for the current release? Any help that you could give me regarding this would be really appreciated!

**Comment by untergasser** [comment]
Hi,
there should be a primer3core file in the src folder, that is the bin. I will update the instructions...
Best,
Andreas
