### ISSUE TITLE
The oligotm tool has been outdated

### ISSUE THREAD

**Issue by billzt** [primer3-org/primer3#23]
The oligotm tools still uses backward compatible calculation. Given this primer pair as an example:
```
Template: CCTGCATAATTCATGAAAAGAGCTTGCCATCCCTCCAGGTAGATATTAATTCTCGCAATCAGTGGTTGTAGTTCAGCAAAATTCAGTTTGGAGCTGGACAACGGAAGCCCGAGACTAGAGTACACCTGGGGGAAATTTTTCTACTTTGCAGTGGAGGATTGCTGCTACTGCTAGAGCTTGAGTTTCAGCACTATCTTGTGGAAGCCTGGAGTTCCTGCTGTAGCCTGTTAGCCATTGCTTTGGCTGTGATCTTGATGGAGCAAATCTGTAGCCGGAGGGACTAGCATAATATGATGAGGATC

Primer F:  AGACTAGAGTACACCTGGGG
Primer R: GCTCCATCAAGATCACAGCC
```

If you use oligotm, the Tm of primer F is 53.30 (still backward compatible calculation)

However, in the output of current version primer3 the Tm of primer F is 57.17

**Comment by bioinfo-ut** [comment]
Thanks.

We updated the default settings of oligotm. 
It now uses the same set of SantaLucia parameters as main primer3_core.
This should fix the issue
