### ISSUE TITLE
ntthal alignment not complete. Incomplete thermodynamic calculation?

### ISSUE THREAD

**Issue by Permafacture** [primer3-org/primer3#24]
ntthal alignment does not show all matching bases as paired.  I am unsure if the thermodynamic calculation considers the matched bases or not either.

After pulling master, `make clean` and `make`, I see this behavior

```
./ntthal -s1 GCTCGCGTCGCCTGCTGCTTTTGGCAGGGTAAAAGA -s2 GCTCGCGTCGCCTGCTGCTTTTGGCAGGGTAAAAGA
Calculated thermodynamical parameters for dimer:        dS = -297.472   dH = -99200     dG = -6939.1    t = 24.1818
SEQ     GCTCGCGTCG     TGCTTTTG     GTAAAAGA--
SEQ               CCTGC        GCAGG
STR               GGACG        CGTCC
STR       AGAAAATG     GTTTTCGT     GCTGCGCTCG
```

The last two 3` bases (for example) on both strands are complementary but not displayed as matches.  There's another T/A match 6 back from the 3` end that is also not shown as a match.  I see this behavior more often than not (I.E. most heterodimers I look at have this happening).

Does this visualization reflect the thermodynamic calculations?  If so, are those matches intentionally excluded? If so, why?

Thanks for reading

(edited get formatting correct)

**Comment by Permafacture** [comment]
This sequence makes it clear to me that this is a bug: tgcgagctataaataatgaaagct

```
TGCGAGCTATAAATAATGAAAGCT----
    ||||                    
    TCGAAAGTAATAAATATCGAGCGT
```

**Comment by triinuk** [comment]
No, this and previous structures are correct ones. You are not familiar with two-state melting and thermodynamics of DNA duplexes. Besides Primer3 articles, do read article "The thermodynamics of DNA structural motifs" by SantaLucia and Hicks, 2004
