### ISSUE TITLE
problem installing on Win10

### ISSUE THREAD

**Issue by liucyuic** [primer3-org/primer3#25]
I also have problem installing it on Win 10:
make
g++ -c -g -Wall -D__USE_FIXED_PROTOTYPES__ -O2 primer3_boulder_main.c
g++ -c -g -Wall -D__USE_FIXED_PROTOTYPES__ -O2 -o format_output.o format_output.c
g++ -c -g -Wall -D__USE_FIXED_PROTOTYPES__ -O2 -o read_boulder.o read_boulder.c
g++ -c -g -Wall -D__USE_FIXED_PROTOTYPES__ -O2 -o print_boulder.o print_boulder.c
g++ -c -g -Wall -D__USE_FIXED_PROTOTYPES__ -O2 masker.c
In file included from /usr/lib/gcc/i686-pc-cygwin/7.3.0/include/c++/i686-pc-cygwin/bits/gthr.h:148:0,
from /usr/lib/gcc/i686-pc-cygwin/7.3.0/include/c++/ext/atomicity.h:35,
from /usr/lib/gcc/i686-pc-cygwin/7.3.0/include/c++/bits/ios_base.h:39,
from /usr/lib/gcc/i686-pc-cygwin/7.3.0/include/c++/ios:42,
from /usr/lib/gcc/i686-pc-cygwin/7.3.0/include/c++/istream:38,
from /usr/lib/gcc/i686-pc-cygwin/7.3.0/include/c++/fstream:38,
from masker.c:1:
/usr/lib/gcc/i686-pc-cygwin/7.3.0/include/c++/i686-pc-cygwin/bits/gthr-default.h: In function ‘int __gthread_mutex_timedlock(__pthread_mutex_t**, const __gthread_time_t*)’:
/usr/lib/gcc/i686-pc-cygwin/7.3.0/include/c++/i686-pc-cygwin/bits/gthr-default.h:768:12: error: ‘pthread_mutex_timedlock’ was not declared in this scope
return _gthrw(pthread_mutex_timedlock) (__mutex, __abs_timeout);
^
/usr/lib/gcc/i686-pc-cygwin/7.3.0/include/c++/i686-pc-cygwin/bits/gthr-default.h:768:12: note: suggested alternative: ‘__gthread_mutex_timedlock’
make: *** [Makefile:226: masker.o] Error 1

**Comment by bioinfo-ut** [comment]
This is duplicate comment
