### ISSUE TITLE
How to exclude specific target regions?

### ISSUE THREAD

**Issue by billzt** [primer3-org/primer3#27]
For example, polyN have trouble to sanger sequencing, therefore it is better not to place primer pairs around it.

The tag `SEQUENCE_EXCLUDED_REGION` is not suitable, as it tells primer3 to exclude **primer overlaping regions**, not **internal regions**

![TIM截图20190626101120](https://user-images.githubusercontent.com/1146090/60146099-d6a0ee80-97fa-11e9-8824-e287abb8d5e6.png)

Take this figure as an example, I want primer A instead of primer B.

Although I can manually extract the amplicon sequences of all the primer pairs, it seems more efficient if we can exclude them in the first step.

**Comment by bioinfo-ut** [comment]
There is no option to directly exclude PCR products containing consecutive N-s.

Perhaps you can define shorter product length?
Or try to achieve the same goal through template masking. Primer3_masker (https://www.ncbi.nlm.nih.gov/pubmed/29360956) is now integrated into Primer3. You could try to mask longer regions in 3'-direction of poly-T, this might help to avoid Primer3 to designing primer pair B.

**Comment by billzt** [comment]
OK, I'll have a try.
