### ISSUE TITLE
How to connect primer 3 with emboss 6.6.0

### ISSUE THREAD

**Issue by aslangabriel** [primer3-org/primer3#28]
Hi，I  tried to relate primer3_core with eprimer3 by creating softlinks under bin folders and export path to emboss_primer3/32_core.  Unfortunately, they didn't work, and always :reported the error that" unable to read sequence; Died: eprimer3/32 terminated: Bad values fpr  sequence and no prompt. My IO platform is ubuntu18.04.
Would you mind fixing it?
Thanks a lot

**Comment by untergasser** [comment]
We are not the developers of emboss. If emboss uses Primer3 and has issues, please contact the emboss developers.

Best, Andreas
