### ISSUE TITLE
Feature request: Multiple structures from thal

### ISSUE THREAD

**Issue by Permafacture** [primer3-org/primer3#30]
I'm using bindings to the primer3 C code and I would like to get multiple structures (in decreasing dG from most stable to some cut off) from thal. I'm curious how difficult this would be, where to look in the current code, and if this is an idea you all have considered and have ideas about. Thanks!

**Comment by bioinfo-ut** [comment]
What would be the purpose of having multiple structures? Is this related to selecting the best primer pair or is it useful for something else?

**Comment by Permafacture** [comment]
The big reason is that from NGS data we know that the most energetically favorable heterodimer is not necessarily the one that will amplify exponentially, and those are the real problem.  In general, the dG is useful through the Boltzman partition function in determining the fraction of primers in that alignment.  So it makes a difference if the second most favorable hairpin structure is a similar dG or much less, because all those structures are competing against it annealing to the correct template.

**Comment by Permafacture** [comment]
So, short answer is that yes it is related to selecting the best primer pair, especially in multiplex.

**Comment by untergasser** [comment]
Hi,
we would be interested if you could identify the amplifying heterodimer by thermodynamic simulations, then we could add a second scoring parameter. Anyway, Primer3 can only report one, the most energetically favorable heterodimer. It will be tricky to return more than one for each primer.
How would a decision between 10 primers, each with 10 secondary structures be made if the most energetically favorable in not the one, but others maybe as well not?
Best,
Andreas

**Comment by Permafacture** [comment]
What I am doing is using machine learning to predict which heterodimer structures will be amplifying.  I don't know that there is a strictly thermodynamic solution to that question, or, if so, it would involve modeling the polymerase also. One inspiration for this work is "The Effect of Single Mismatches on Primer Extension" by Rejali, et al. (https://academic.oup.com/clinchem/article/64/5/801/5608698) 

Asking to propose a solution for choosing which structure is most harmful is putting the cart before the horse because it would require that I've had experience with vetting lists of structures without having software that gives me a list of structures. Having access to the top N energetically favorable structures would help researchers propose solutions to the question of which one of all the structures is the most problematic.

**Comment by bioinfo-ut** [comment]
I would suggest using Unafold (http://www.unafold.org/) for calculating all reasonably likely secondary structures. Primer3 is not designed to do this.
