### ISSUE TITLE
Return all primers for pick_sequencing_primers task

### ISSUE THREAD

**Issue by shunhuahan** [primer3-org/primer3#32]
- I noticed that only one primer would be returned if the task is `pick_sequencing_primers`, instead of a list of primer candidates, even if I ask primer3 to return multiple primers using `PRIMER_NUM_RETURN`.

- I checked the source code and the it appears that the one primer return behavior is enforced by using `pick_only_best_primer` function (which is only used when pick sequencing primers ) . https://github.com/primer3-org/primer3/blob/43c33e474ba4e70567b72486037feca669eee28f/src/libprimer3.cc#L2420

- My question: Is there any specific reason to return only the "best primer" for `pick_sequencing_primers` task, and is it possible to update primer3 so that returning multiple primer candidates is an option (e.p. using `pick_primer_range` function)?

Thanks!

**Comment by untergasser** [comment]
The pick_sequencing_primers function picks a single primer per position, the best. The user does not have to sort primers afterwards an can just order. If you are interested to obtain several primers, you could create primer lists of that region and sort them by yourself.

Best,

Andreas
