### ISSUE TITLE
Crash in check_primers if primers are perfect match

### ISSUE THREAD

**Issue by Curley-Joe** [primer3-org/primer3#33]
Primer3 version: 2.5.0

Input file:

PRIMER_TASK=check_primers
SEQUENCE_PRIMER=CACCCCCATCAAACTCTTACTCA
SEQUENCE_PRIMER_REVCOMP=TGAGTAAGAGTTTGATGGGGGTG
\=

Output:

temporaryprimer3:libprimer3.cc:4065, assertion (ppair->right->start - ppair->left->start + 1 > 0) failed
Aborted (core dumped)

**Comment by untergasser** [comment]
Thank you for reporting this. It does not make sense to provide the same or the reverse complement of the left primer in right primer.

This will now throw an error from this commit on:

https://github.com/primer3-org/primer3/commit/9660639e9068a77dd8bb6fc4c0664ba3ec34ee29

Best,

Andreas

**Comment by Curley-Joe** [comment]
Actually it does make sense if you want to calculate the melting temperature. At the time (Feb 23, 2020) I was trying to use primer3 to calculate the melting temperatures of a large batch of primer pairs, and ntthal didn't have a batch mode. But I ended up converting ntthal to Java to solve my problem.

**Comment by untergasser** [comment]
No, you should use Primer3 with the task check_primers and without sequence for this use. It takes one to three oligos and the sequence is optional. Then it will not crash.
