### ISSUE TITLE
Question on calcHairpin dg discrepancy 

### ISSUE THREAD

**Issue by sooheelee** [primer3-org/primer3#38]
I'm observing a discrepancy in the dg given by calcHairpin for 'TTAACCTCAGATCCTAAGCCGCACAAAGTTGCGGCTTAGGATCTGA', a sequence from a paper I am reading.

![image](https://user-images.githubusercontent.com/11543866/89454081-2b1cda00-d72e-11ea-926a-823ac014072e.png)

- In blue is primer3's hairpin dg on y and primer3's hairpin Tm on x for four sequences including that above, which is the last datapoint.
- In orange is another software package's hairpin dg on y.
- The slight offset is due to minor differences in parameterization. 
- Three of the sequences give concordant dgs for the two softwares

I expect the dgs to correlate with each other and to the hairpin Tm. Any idea why I see an aberration for this particular sequence?

Thank you for your time.

**Comment by sooheelee** [comment]
@untergasser ^

**Comment by bioinfo-ut** [comment]
I don't understand what are you trying to achieve with this analysis.
Primer3 is NOT a software for calculation of hairpins and their strength. It's primary purpose is to design PCR primers that won't fail.
Are you using this sequence as a PCR primer? Did it fail in an experiment?

If you want to calculate accurate secondary structures for DNA sequences of any length, then I would rather suggest MFOLD:
http://unafold.rna.albany.edu/?q=mfold/DNA-Folding-Form

**Comment by RitahNabunje** [comment]
@bioinfo-ut  Is it okay using `ntthal` to obtain dG values for the formed secondary structures? Also, are the dG values in cal/mol or kcal/mol?
