### ISSUE TITLE
Question re TEMPLATE_MISPRIMING parameters

### ISSUE THREAD

**Issue by genya** [primer3-org/primer3#43]
is there a way to restrict the consideration of primer mispriming to a certain number of bases from the 3' end of the primer? In other words, make it so that the PRIMER_MAX_TEMPLATE_MISPRIMING parameter ("The maximum allowed similarity to ectopic sites in the template. ") only takes into account a specified portion of the primer nearest the 3' end. Is that possible?

**Comment by bioinfo-ut** [comment]
I am not sure.
But perhaps Primer3_masker would help you in this case?
There you can define k-mer length ("specified portion") that is used for finding binding sites in the template.
Primer3_masker: integrating masking of template sequence with primer design software
https://github.com/bioinfo-ut/primer3_masker
https://academic.oup.com/bioinformatics/article/34/11/1937/4817620
