### ISSUE TITLE
Multiplexing assays takes a lot of time

### ISSUE THREAD

**Issue by haseebz** [primer3-org/primer3#45]
Running the `primer3_core` , `primer_tk pre`  takes a lot of time. Is there a way to improve processing and decrease time? This will really help with the purpose of using Primer TK when we are looking to design primers for multiplexed assays.

**Comment by untergasser** [comment]
Hi,

we develop Primer3 and have nothing to do with Primer TK. Primer3 runs usually in milliseconds, so it is as fast as it can get.
Of course we are open to a pull request with speed enhancements if you have good ideas for a speedup.

Best,

Andreas

**Comment by haseebz** [comment]
Thanks, Andreas. Sorry for posting it here. Primer 3 is awesome :)
