### ISSUE TITLE
Stray text NOWWW in manual

### ISSUE THREAD

**Issue by peterjc** [primer3-org/primer3#46]
Quoting https://github.com/primer3-org/primer3/blob/master/src/primer3_manual.htm

```
<br>
WARNING: always set <a href="#PRIMER_LIB_AMBIGUITY_CODES_CONSENSUS">PRIMER_LIB_AMBIGUITY_CODES_CONSENSUS</a>=0
if any sequence in the library contains strings of 'N's:
NNNNNNNNNNNNNNNNNNNN.<br>
NOWWW<br>
There are no restrictions on line length.<br>
<br>
```

The ``NOWWW`` should probably simply be removed leaving a line break only.

**Comment by untergasser** [comment]
Hi,

thank you for the hint, I removed it in the sources for the docs. It will be gone in the next version.

Best,

Andreas
