### ISSUE TITLE
How to set the SEQUENCE_TARGET or SEQUENCE_EXCLUDED_REGION parameter?

### ISSUE THREAD

**Issue by sen1019san** [primer3-org/primer3#47]
I am trying to design primers for a sequence that contains a target region in 200-700 bp position.  Here shows a diagram: 
![image](https://user-images.githubusercontent.com/43125963/128120466-5b750440-db4c-49ff-ab5b-5f90ee642d35.png)

I have tried to set  _SEQUENCE_TARGET=200,300_ or _SEQUENCE_EXCLUDED_REGION=200,300_ expecting PCR amplicon covers the target region. But primer3 (v2.5.0)  only return primer pairs that overlap the target region.
How can I change the parameters?

Here are the parameters options: 
[primer3_test.txt](https://github.com/primer3-org/primer3/files/6928539/primer3_test.txt)
```
SEQUENCE_TARGET=200,300
PRIMER_TASK=generic
PRIMER_PICK_LEFT_PRIMER=1
PRIMER_PICK_RIGHT_PRIMER=1
PRIMER_NUM_RETURN=5
PRIMER_MAX_NS_ACCEPTED=0
PRIMER_PRODUCT_SIZE_RANGE=500-800
PRIMER_THERMODYNAMIC_PARAMETERS_PATH=/home/lhs/softwares/primer3-master/src/primer3_config/
PRIMER_THERMODYNAMIC_OLIGO_ALIGNMENT=1
PRIMER_THERMODYNAMIC_TEMPLATE_ALIGNMENT=1
PRIMER_MAX_SELF_ANY_TH=20.00
PRIMER_PAIR_MAX_COMPL_ANY_TH=20.00
PRIMER_MAX_SELF_END_TH=20.00
PRIMER_PAIR_MAX_COMPL_END_TH=20.00
PRIMER_MAX_HAIRPIN_TH=20.00
PRIMER_OUTSIDE_PENALTY=-1.0
PRIMER_EXPLAIN_FLAG=1
P3_FILE_FLAG=1
=
SEQUENCE_ID=test1
SEQUENCE_TEMPLATE=ACCCTATTTCCACCTATCCAAAATGGAGAAAGTTCATGTTGACTTAGACGCAGACAGCCCATTCGTCAAGTCACTGCAAAGATGCTTTCCACATTTTGAGATAGAAGCAACGCAGGTCACTGACAATGACCATGCTAATGCTAGGGCGTTTTCGCACCTAGCTACTAAGCTCATTGAGGGAGAAGTGGATACAGACCAGGTGATCCTGGATATCGGGAGCGCGCCTGTAAGGCACACGCATTCCAAACATAAGTACCACTGCATTTGCCCAATGAAGAGCGCAGAAGACCCTGACAGACTCTACCGCTACGCAGACAAGCTTAGAAAGAGTGATGTCACTGACAAATGTATTGCCTCTAAGGCCGCGGACCTGCTAACAGTAATGTCGACGCCTGACGCTGAGACACCCTCGTTATGCATGCACACTGACTCAACTTGCAGGTACCACGGCTCCGTGGCCGTATATCAGGATGTATATGCAGTGCATGCACCGACTTCCATTTACTACCAGGCGCTGAAAGGTGTACGAACTATCTATTGGATCGGGTTCGATACTACACCGTTCATGTATAAGAACATGGCAGGCGCCTACCCTACATACAACACTAATTGGGCCGATGAAAGTGTGTTGGAAGCCAGAAATATAGGGCTGGGTAGTTCAGACTTGCACGAAAAGAGTTTCGGAAAAGTATCCATTATGAGGAAGAAGAAATTACAACCCACCAATAAAGTAATATTTTCTGTGGGGTCAACTATTTATACTGAAGAGAGAATACTGTTACGCAGTTGGCATCTACCTAATGTTTTTCATCTAAAAGGTAAAACTAGCTTTACAGGCAGATGTAACACTATCGTCAGCTGCGAAGGTTACGTTGTCAAGAAGATTACGCTCAGTCCTGGGATTTACGGGAAAGTGGATAATCTTGCTTCGACCATGCACCGAGAGGGATTCTTAAGTTGCAAGGTTACAGATACGTTAAGAGGGGAGAGGGTCTCTTTT
=

```

The results show that primer3 failed to design primer pairs cover the target region:
[primer3_test.p3.txt](https://github.com/primer3-org/primer3/files/6928563/primer3_test.p3.txt)
```
PRIMER_LEFT_0=296,20
PRIMER_RIGHT_0=876,20

PRIMER_LEFT_1=292,20
PRIMER_RIGHT_1=876,20

PRIMER_LEFT_2=294,20
PRIMER_RIGHT_2=876,20

PRIMER_LEFT_3=296,20
PRIMER_RIGHT_3=874,20

PRIMER_LEFT_4=292,20
PRIMER_RIGHT_4=874,20

```

Any answers are appreciated.

**Comment by untergasser** [comment]
Hi,

there are some issues. Primer3 memorizes PRIMER_* tag though a run, SEQUENCE_* tags only for the current sequence, so they have to be provided each time. A single = forces a calculation, so the first is missing a sequence and it throws an error:
PRIMER_ERROR=Need PRIMER_SEQUENCE_ID if PRIMER_FILE_FLAG is not 0

The second = forgot about the SEQUENCE_TARGET=200,300 so it is fine.

Here is a fix with some adaptions:
[fixed.txt](https://github.com/primer3-org/primer3/files/6928718/fixed.txt)

I hope that clears things up a bit.

Best,

Andreas
