### ISSUE TITLE
What is the difference between primer3web and primer3Plus ?

### ISSUE THREAD

**Issue by ptranvan** [primer3-org/primer3#50]
Hi, 

Thanks for your software.
What is the difference between primer3web and primer3Plus ? is one give "better results" than the other ?

Where can I find the primer3Plus setting file ?

Thanks !

**Comment by untergasser** [comment]
Hi,

Primer3web is the more basic, classic interface. Primer3Plus is the more modern and interactive interface.
Primer3Plus allows to download the current settings on the general settings tab.

The results depend on the settings and are identical with identical settings in both interfaces.

Best,

Andreas
