### ISSUE TITLE
how to determine the integer input for SEQUENCE_OVERLAP_JUNCTION_LIST

### ISSUE THREAD

**Issue by juechenyang** [primer3-org/primer3#53]
Hi,

I have a question regarding to how to determine the integer input for SEQUENCE_OVERLAP_JUNCTION_LIST. Suppose I have a gene which have 3 exons with their length of 10,12,15 respectively. In this case, what should be the input integer for SEQUENCE_OVERLAP_JUNCTION_LIST? Is it something like "10 22 37" where 22 is first two exon's length and 37 is the all three's. If yes, what if this gene is on reverse strand? Is this going to be a different integer list?

Thank you

**Comment by untergasser** [comment]
See the Manual:
https://primer3.org/manual.html#SEQUENCE_OVERLAP_JUNCTION_LIST

The idea is to use a cDNA without introns, so they are removed from the sequence.
"10 22 37" means 10-11, 22-23 and 37-38 are the junctions where the introns were before removal.

Best,

Andreas

**Comment by untergasser** [comment]
Primer3 takes one sequence. It does not know about introns and exons. The positions are for this sequence and it tries to overlap them as defined by the other parameters.

So for your example you remove the introns from the sequence and use:
10000 20000 30000

Best,

Andreas
