### ISSUE TITLE
thal.c caused crash of build on ubuntu, "/0" needs to be just zero 

### ISSUE THREAD

**Issue by sebogawa** [primer3-org/primer3#55]
![Screenshot 2021-11-28 10 42 10 AM](https://user-images.githubusercontent.com/8923642/143775574-c46d826f-261f-42d4-aa2e-2aec5bd6b8b7.png
![Screenshot 2021-11-28 10 49 03 AM](https://user-images.githubusercontent.com/8923642/143775579-7987949b-d7d4-439d-a883-5bf6d78dd443.png)
![photo4981488930771806642](https://user-images.githubusercontent.com/8923642/143775620-210b343a-d989-4125-9df9-350d5ad59b28.jpg)
)
![Screenshot 2021-11-28 10 40 42 AM](https://user-images.githubusercontent.com/8923642/143775657-c835ed6f-ca53-4b0f-ad64-9096afc173a1.png)

**Comment by untergasser** [comment]
Please update to current version. Version 2.4.0 will not be fixed.
