### ISSUE TITLE
Could primer3 design primers based on alignment

### ISSUE THREAD

**Issue by starsareintherose** [primer3-org/primer3#56]
In the documents, I see, I can use multi templates in the file, such as so
```
SEQUENCE_ID=test1
SEQUENCE_TEMPLATE=GACTGATCGATGCTAGCTACGATCGATCGATGCATGCTAGCTAGCTAGCTGCTAGC
=
SEQUENCE_ID=test2
SEQUENCE_TEMPLATE=CATCATCATCATCGATGCTAGCATCNNACGTACGANCANATGCATCGATCGT
=
SEQUENCE_ID=test3
SEQUENCE_TEMPLATE=NACGTAGCTAGCATGCACNACTCGACNACGATGCACNACAGCTGCATCGATGC
=
```
But they produce separate results for themselves one by one, not considering them as alignment, or what should I do to design primers based on alignment
My setting is here.
```
PIMER_TASK=generic
PRIMER_PICK_LEFT_PRIMER=1
PRIMER_PICK_INTERNAL_OLIGO=1
PRIMER_PICK_RIGHT_PRIMER=1
PRIMER_OPT_SIZE=20
PRIMER_MIN_SIZE=15
PRIMER_MAX_SIZE=26
PRIMER_MAX_NS_ACCEPTED=0
PRIMER_PRODUCT_SIZE_RANGE=500-600
SEQUENCE_EXCLUDED_REGION=500,900
PRIMER_EXPLAIN_FLAG=1
=
```

**Comment by bioinfo-ut** [comment]
Make a consensus sequence from alignment and use that as a template.

**Comment by starsareintherose** [comment]
But sometimes it is essential because we cannot always get a consensus sequence from alignment.

**Comment by untergasser** [comment]
Primer3 will only pick primers based on one input sequence. It is up to the user to provide this sequence. Primer3 does not create a consensus, as it only handles one sequence a time...

Best,

Andreas
