### ISSUE TITLE
critical memory error

### ISSUE THREAD

**Issue by jocelyne8** [primer3-org/primer3#58]
Hello, 
Thank you again for the prompt fix of #57. I re-ran the full suite with release 2.6.0 and we now have a much higher success rate. We still have a memory error in one case (attached). I don't know if it's related or not.
Please let me know if there's any other information I can provide.
Jocelyne

```
*** Error in `primer3_core': corrupted size vs. prev_size: 0x00005623d9247e20 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7f3e4)[0x2aff71f0a3e4]
/lib64/libc.so.6(+0x814db)[0x2aff71f0c4db]
primer3_core(+0x13ead)[0x5623d5b36ead]
primer3_core(+0x13f41)[0x5623d5b36f41]
primer3_core(+0x2ac4)[0x5623d5b25ac4]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x2aff71ead555]
primer3_core(+0x326d)[0x5623d5b2626d]
```

[primer3_input.target_9.txt](https://github.com/primer3-org/primer3/files/7849549/primer3_input.target_9.txt)

**Comment by untergasser** [comment]
Hi Jocelyne,

usually we are not so fast in responding (I do not want to get expectations to high), but you were luck that I was in the middle of preparing a release. So here is the hopefully final fix of the same bug you reported before:
https://github.com/primer3-org/primer3/commit/53734b8a1c5ec61da7a5fbf6c1ae68f0033fa9c6
You can use it from source, I will prepare a release in a few days if time permits.

Best,
Andreas

**Comment by jocelyne8** [comment]
Hi Andreas,
I completely understand. I was mind-blown by the response time and told our entire Bioinformatics team :) It was well beyond any expectation. One of our team members is a firm believer that you should always file issues when you find them. As a freeloader of your software, I owe you that, even if no one has the time to look at it in the near future.
In short, I didn't and don't expect a prompt turn-around time; and I am extremely grateful. Thank you.

Of course, I also owe you to test the bug fix :) I'm happy to inform you that I built from source and that I was able to run that dataset through!

Thank you again!

Jocelyne

PS: I now have 2 data points for "amazing response time" ;)

**Comment by jocelyne8** [comment]
The build I made from source has been very stable. Thank you. I'll close this issue; please let me know if you make a release!

**Comment by jocelyne8** [comment]
I see 2.6.1 is out! Thank you so very much!
