### ISSUE TITLE
Segmentation fault 

### ISSUE THREAD

**Issue by Princysaini** [primer3-org/primer3#60]
Hello,
I was using the primer 3 tool, it gave me an error. 

/var/spool/PBS/mom_priv/jobs/12496.hn01.SC: line 9: 219810 Segmentation fault      (core dumped) perl p3_in.pl assembly.fasta.misa

pl, let me know how can I solve this issue.
Thanks in advance.

**Comment by untergasser** [comment]
Hi,

p3_in.pl is not our program. You need to find out which program you use, if it is Primer3 (our program) and which version. If you used Primer3, provide the complete problematic input of Primer3 to us. Else we can not recreate and fix the bug.

Best,

Andreas
