### ISSUE TITLE
unable to open file /opt/primer3_config/stack.ds

### ISSUE THREAD

**Issue by Hytham79** [primer3-org/primer3#61]
I am trying to use a script to call primers posted on eulaf/cardio_padlock github page . I had primer3_core issue as not found in the beginning and I ended up setting the path correctly. Now when I run the script again, I get the error above. The P3CONFIG PATH is written as follow "/opt/primer3_config/". I am looking for some help to find a solution to pass that error. Note* I am using the virtual box with ensembl105 included. Thank you

**Comment by untergasser** [comment]
You are missing the primer3_config folder which comes with Primer3. I think this is more a question for eulaf/cardio_padlock to fix their script.

Best, Andreas

**Comment by Hytham79** [comment]
I do have the primer3_config folder included in the primer3-2.4.0 version I downloaded. It has group of files where stack.ds file among them.

**Comment by untergasser** [comment]
So we did all we could with Primer3. I still would recommend to get the latest version of Primer3. The rest is in the responsibility of eulaf/cardio_padlock which sets most likely the path somewhere. Good luck!

Best, Andreas

**Comment by Hytham79** [comment]
Thanks for your feed back.

**Comment by Hytham79** [comment]
I see three assets"primer3-2.6.1_exe_for_windows.zip, source code(zip), and source code(tar.gz)" under the new version. which one I should download and works for Linux? I am using the virtual box. Thanks for your time

**Comment by untergasser** [comment]
Why not build from source? Follow the steps to install:
https://github.com/primer3-org/primer3

If you have the latest version, search for the parameter PRIMER_THERMODYNAMIC_PARAMETERS_PATH in your script and delete the line. Primer3 will use the internal version.

**Comment by Hytham79** [comment]
As always, thanks for your feed back. I am trying to download primer3 from the source given, but I am being asked to enter a password for ensemble which I am not aware off! Also, In the call primers script, there is a line says, "my $p ={ P3EXE=>'primer3 core path' and "P3CONFIG_ PATH =>'/opt/primer3_config/' an the rest of the parameters. Any changes I need to make here? I notice another line says, "$P3_PARAMS{PRIMER_THERMODYNAMIC_PARAMETERS_PATH=$$P{P3CONFIG_PATH} among codes for $P3_PARAMS
{PRIMER_PRODUCT_SIZE_RANGE}=. Should I delete it?  Last, what is the preferred location to download primer3 and do I have to locate any of its contents like primer3_core into "bin" folder for instance. Thank you.

**Comment by Hytham79** [comment]
Thank you for your help. That solved the issue
