### ISSUE TITLE
Signal 11 segmentation fault in thal.c

### ISSUE THREAD

**Issue by InvisOn** [primer3-org/primer3#65]
I'm trying to use primer3 from Julia but I'm getting a segmentation fault whenever I try to call thal() from thal.c

I've made a repo to recreate the issue.

https://github.com/InvisOn/recreate_primer3_segfault

**Comment by untergasser** [comment]
Hi,

I have no experience with debugging Julia. If you could create input which creates the bug using the binaries from our repo, I could have a look.

Best,

Andreas

**Comment by InvisOn** [comment]
I managed to fix my issue by writing a helper function to initializes thal() parameters and call thal() with them. It seems the problem was my lack of C knowledge. Nothing a good ol' rousing round of learning C couldn't fix.
