### ISSUE TITLE
What PRIMER_PRODUCT_OPT_SIZE is needed for?

### ISSUE THREAD

**Issue by DmitriiSukhomlinov** [primer3-org/primer3#67]
How should I use `PRIMER_PRODUCT_OPT_SIZE`? Is that the same as `PRIMER_OPT_SIZE` or have some difference? Reading the manual I've got a suggestion, that it's kinda an optimum size for Penalty Weights for Primer Pairs, but I'm not clearly sure. Also, why is this parameter isn't presented into a [Web version](https://primer3.ut.ee/) of Primer3?

**Comment by untergasser** [comment]
You should not use PRIMER_PRODUCT_OPT_SIZE as it makes calculations very slow. You can define the exact length of the product with this tag. You should use the ranges instead: PRIMER_PRODUCT_SIZE_RANGE.

PRIMER_OPT_SIZE gives the optimal size of a primer.

As PRIMER_PRODUCT_OPT_SIZE slows down calculations dramatically, it is not accessible via the web interface.

Best,

Andreas

**Comment by DmitriiSukhomlinov** [comment]
Thank you so much, I got it
