### ISSUE TITLE
Abnormal primer positions

### ISSUE THREAD

**Issue by shiyi-pan** [primer3-org/primer3#71]
Hi, I want to use primer3 to design some PCR primer. I use SEQUENCE_PRIMER_PAIR_OK_REGION_LIST to set primer positions, but it doesn't work.

Here is my input file:

SEQUENCE_ID=INS52546
SEQUENCE_TEMPLATE=TGCAGAGATGCTTGACCCGGCCATTCCTGACTGGCCACTCGAACAGACCTTGCATTTCGCCAAGCTTTCCCTCGGATGCGCCGAGATGAGAAGAAAAGATCGACCAGATCTTGGAAAAGTTGTGTTGCCGGAGCTCAATAAGCTTAGGGCATTTGCTGAACAATGCATGTCACCTATGATGATGTTTGCACTTAGAAGTACTGGTGGTGGTGGTGGTGGTGCAGGATATGTTCCCAGAAACAGTAACTCTTCCGGACTTTCTTCTTCAACTCAAGTGAGTCATGCATGCATGCATGTACACACATTCATTAATTTCTTTTTCTTTTTCTTTTGAACTTGGATAATCATCAAATGAATGAATGATCAATGCTGTGTTGTAGGACATGAGTGAAGTGTCTGGC
PRIMER_TASK=generic
PRIMER_PICK_LEFT_PRIMER=1
PRIMER_PICK_INTERNAL_OLIGO=0
PRIMER_PICK_RIGHT_PRIMER=1
PRIMER_OPT_SIZE=20
PRIMER_MIN_SIZE=18
PRIMER_MAX_SIZE=22
PRIMER_PRODUCT_SIZE_RANGE=100-350
SEQUENCE_PRIMER_PAIR_OK_REGION_LIST=0,150,250,150
PRIMER_EXPLAIN_FLAG=1
PRIMER_THERMODYNAMIC_OLIGO_ALIGNMENT=1

and here is my seting file:

Primer3 File - http://primer3.sourceforge.net
P3_FILE_TYPE=settings

P3_FILE_ID=P3 Settings from Lianfu Chen
PRIMER_FIRST_BASE_INDEX=1
PRIMER_TASK=generic
PRIMER_NUM_RETURN=5
PRIMER_PICK_LEFT_PRIMER=1
PRIMER_PICK_INTERNAL_OLIGO=0
PRIMER_PICK_RIGHT_PRIMER=1
PRIMER_PICK_ANYWAY=1
PRIMER_THERMODYNAMIC_PARAMETERS_PATH=/ds3512/home/panyp/ruanjian/primer3/src/primer3_config/

SEQUENCE_PRIMER_PAIR_OK_REGION_LIST=0,150,250,150

PRIMER_TM_FORMULA=1
PRIMER_MIN_TM=55.0
PRIMER_OPT_TM=60.0
PRIMER_MAX_TM=65.0
PRIMER_PAIR_MAX_DIFF_TM=5.0
PRIMER_WT_TM_LT=0
PRIMER_WT_TM_GT=0
PRIMER_PAIR_WT_DIFF_TM=0.0

PRIMER_MIN_SIZE=18
PRIMER_OPT_SIZE=20
PRIMER_MAX_SIZE=22
PRIMER_WT_SIZE_LT=0
PRIMER_WT_SIZE_GT=0

PRIMER_MIN_GC=30.0
PRIMER_MAX_GC=70.0
PRIMER_WT_GC_PERCENT_LT=0.0
PRIMER_WT_GC_PERCENT_GT=0.0

PRIMER_THERMODYNAMIC_OLIGO_ALIGNMENT=1

PRIMER_MAX_SELF_ANY=8.00
PRIMER_WT_SELF_ANY=0.0
PRIMER_MAX_SELF_ANY_TH=45.00
PRIMER_WT_SELF_ANY_TH=123.2

PRIMER_MAX_SELF_END=3.00
PRIMER_WT_SELF_END=0.0
PRIMER_MAX_SELF_END_TH=35.00
PRIMER_WT_SELF_END_TH=302.4

PRIMER_PAIR_MAX_COMPL_ANY=8.00
PRIMER_PAIR_WT_COMPL_ANY=0.0
PRIMER_PAIR_MAX_COMPL_ANY_TH=45.00
PRIMER_PAIR_WT_COMPL_ANY_TH=123.2

PRIMER_PAIR_MAX_COMPL_END=3.00
PRIMER_PAIR_WT_COMPL_END=0.0
PRIMER_PAIR_MAX_COMPL_END_TH=35.00
PRIMER_PAIR_WT_COMPL_END_TH=302.4

PRIMER_MAX_HAIRPIN_TH=24.00
PRIMER_WT_HAIRPIN_TH=672

PRIMER_MAX_END_STABILITY=9.0
PRIMER_WT_END_STABILITY=1

PRIMER_LOWERCASE_MASKING=0
PRIMER_MAX_POLY_X=4
PRIMER_MAX_NS_ACCEPTED=0
PRIMER_WT_NUM_NS=0.0
PRIMER_MAX_END_GC=5
PRIMER_GC_CLAMP=0
PRIMER_LIBERAL_BASE=1
PRIMER_LIB_AMBIGUITY_CODES_CONSENSUS=0

PRIMER_MIN_QUALITY=0
PRIMER_MIN_END_QUALITY=0
PRIMER_QUALITY_RANGE_MIN=0
PRIMER_QUALITY_RANGE_MAX=100
PRIMER_WT_SEQ_QUAL=0.0
PRIMER_WT_END_QUAL=0.0

PRIMER_SEQUENCING_LEAD=50
PRIMER_SEQUENCING_SPACING=500
PRIMER_SEQUENCING_INTERVAL=250
PRIMER_SEQUENCING_ACCURACY=20
PRIMER_OUTSIDE_PENALTY=0
PRIMER_INSIDE_PENALTY=-1.0
PRIMER_WT_POS_PENALTY=0.0

PRIMER_SALT_MONOVALENT=50.0
PRIMER_SALT_CORRECTIONS=1
PRIMER_SALT_DIVALENT=1.5
PRIMER_DNTP_CONC=0.6
PRIMER_DNA_CONC=50.0

PRIMER_PAIR_WT_PR_PENALTY=1.0
PRIMER_PAIR_WT_IO_PENALTY=0.0

PRIMER_INTERNAL_MIN_TM=57.0
PRIMER_INTERNAL_OPT_TM=60.0
PRIMER_INTERNAL_MAX_TM=63.0
PRIMER_INTERNAL_WT_TM_LT=1.0
PRIMER_INTERNAL_WT_TM_GT=1.0

PRIMER_INTERNAL_MIN_SIZE=18
PRIMER_INTERNAL_OPT_SIZE=20
PRIMER_INTERNAL_MAX_SIZE=27
PRIMER_INTERNAL_WT_SIZE_LT=1.0
PRIMER_INTERNAL_WT_SIZE_GT=1.0

PRIMER_INTERNAL_MIN_GC=20.0
PRIMER_INTERNAL_MAX_GC=80.0
PRIMER_INTERNAL_OPT_GC_PERCENT=50.0
PRIMER_INTERNAL_WT_GC_PERCENT_LT=0.0
PRIMER_INTERNAL_WT_GC_PERCENT_GT=0.0

PRIMER_INTERNAL_MAX_SELF_ANY=12.00
PRIMER_INTERNAL_WT_SELF_ANY=0.0
PRIMER_INTERNAL_MAX_SELF_END=12.00
PRIMER_INTERNAL_WT_SELF_END=0.0

PRIMER_INTERNAL_MAX_POLY_X=5
PRIMER_INTERNAL_MAX_NS_ACCEPTED=0

PRIMER_INTERNAL_MIN_QUALITY=0
PRIMER_INTERNAL_WT_END_QUAL=0.0
PRIMER_INTERNAL_WT_SEQ_QUAL=0.0

#PRIMER_INTERNAL_MAX_LIBRARY_MISHYB=12.00
#PRIMER_INTERNAL_WT_LIBRARY_MISHYB=0.0

PRIMER_INTERNAL_SALT_MONOVALENT=50.0
PRIMER_INTERNAL_SALT_DIVALENT=1.5
PRIMER_INTERNAL_DNA_CONC=50.0
PRIMER_INTERNAL_DNTP_CONC=0.0
=

Here is part of my results:

SEQUENCE_ID=INS52164
SEQUENCE_TEMPLATE=GTGTGCGGTGGCGTGAGACAATGGAGGGGGCCATTTTCATGTTTTGAAGTCAAAGAATCCAAAAACAATAGTCCCGTTTAGGGTTTAAACAACTTTAAAAAAAACAAATTTTGAAAATCCAAAAAAAAATAGGAAATCGATTTTTTTCCATGTTCAAGTACCCATGTTTGGGATTTTTTTTTTTTGGGTGGGTTATGGGTTTGAGACATTGGAGGGCAGTCATTTCTCATGTTTGGACGTCAAAGAACCCAAAACAAATAGTCCCGTTCCCCGGATACGTCAACTAACACGTAATAACAAAGCCTGAAAATAAAATAAAAAAGGAAATCGATCCTTTTCCATGTTCAAGTACCCATGTTTGGGATTTTTTTCCTTGGGTGTGCCAGTGGCGTGATACAATT
PRIMER_TASK=generic
PRIMER_PICK_LEFT_PRIMER=1
PRIMER_PICK_INTERNAL_OLIGO=0
PRIMER_PICK_RIGHT_PRIMER=1
PRIMER_OPT_SIZE=20
PRIMER_MIN_SIZE=18
PRIMER_MAX_SIZE=22
PRIMER_PRODUCT_SIZE_RANGE=100-350
SEQUENCE_PRIMER_PAIR_OK_REGION_LIST=0,150,250,150
PRIMER_EXPLAIN_FLAG=1
PRIMER_FIRST_BASE_INDEX=1
PRIMER_NUM_RETURN=5
PRIMER_THERMODYNAMIC_OLIGO_ALIGNMENT=1
PRIMER_THERMODYNAMIC_PARAMETERS_PATH=/ds3512/home/panyp/ruanjian/primer3/src/primer3_config/
PRIMER_WARNING=PRIMER_PAIR_OK_REGION_LIST outside of INCLUDED_REGION
PRIMER_LEFT_EXPLAIN=considered 1324, GC content failed 475, low tm 370, high tm 20, high hairpin stability 196, long poly-x seq 66, not in any ok left region 1, ok 196
PRIMER_RIGHT_EXPLAIN=considered 1430, GC content failed 136, low tm 199, high tm 30, high hairpin stability 158, long poly-x seq 24, not in any ok right region 855, ok 28
PRIMER_PAIR_EXPLAIN=considered 5488, unacceptable product size 2017, tm diff too large 199, high any compl 26, high end compl 17, ok 3229
PRIMER_LEFT_NUM_RETURNED=5
PRIMER_RIGHT_NUM_RETURNED=5
PRIMER_INTERNAL_NUM_RETURNED=0
PRIMER_PAIR_NUM_RETURNED=5
PRIMER_PAIR_0_PENALTY=53.185011
PRIMER_LEFT_0_PENALTY=21.919872
PRIMER_RIGHT_0_PENALTY=23.163556
PRIMER_LEFT_0_SEQUENCE=GACATTGGAGGGCAGTCATTTC
PRIMER_RIGHT_0_SEQUENCE=TGGGTACTTGAACATGGAAAAG
PRIMER_LEFT_0=205,22
PRIMER_RIGHT_0=355,22
PRIMER_LEFT_0_TM=59.575
PRIMER_RIGHT_0_TM=56.533
PRIMER_LEFT_0_GC_PERCENT=50.000
PRIMER_RIGHT_0_GC_PERCENT=40.909
PRIMER_LEFT_0_SELF_ANY_TH=0.00
PRIMER_RIGHT_0_SELF_ANY_TH=0.00
PRIMER_LEFT_0_SELF_END_TH=0.00
PRIMER_RIGHT_0_SELF_END_TH=0.00

The LEFT primer should be in 0-150bp and it's at 205 bp. Could you help me solve this problem? 
Thank you very much.

**Comment by ChrisLou-bioinfo** [comment]
I have the same problem

**Comment by lalalagartija** [comment]
Same here. It does not seem to be a problem for the web interface meaning they need to update also the command-line tool

**Comment by lalalagartija** [comment]
I had the same issue. It was due to the fact that the right primer position is the 5' so it ends at start - length... maybe you are not having the same issue ?

**Comment by untergasser** [comment]
It is that PRIMER_FIRST_BASE_INDEX=1 and you start your region at 0, so position -1, which is the signal to not use it.

I created a fix avoiding negative positions: "Fix not allowing negative positions after first index correction"

Best,
Andreas
