### ISSUE TITLE
A question about picking sequencing primers

### ISSUE THREAD

**Issue by yangjw1996** [primer3-org/primer3#72]
Hi, I am using primer3 to design primers of nested PCR for the next generation sequencing.
For example, I would like to sequence a gene which is about 10000 bp long. Assume that the first pair of primers is 'pairA', the next pair of primer is 'pairB'. I will let the left primer of 'pairB' located before the right primer of 'pairA', and 'pairA' and 'pairB' will be assigned to different groups in PCR experiment. Such way of designing primers is called nested PCR.  I think nested PCR is similar with normal PCR, but in the range of an amplicon, nested PCR require four primers , two primers are in the same pair, two primers are in another two pairs. 

I  wonder if primer3 may be able to design primers of nested PCR if  'PRIMER_TASK'  is set to 'pick_sequencing_primers'. If it is able to do such thing, how should I set the parameters to adapt to different sequencing lengths in NGS platforms?

I have did some tests but I don't know if I did it right. Can you explain these two parameters : 'PRIMER_SEQUENCING_SPACING' and 'PRIMER_SEQUENCING_INTERVAL'.  In default setting,  'PRIMER_SEQUENCING_SPACING' is 500 and 'PRIMER_SEQUENCING_INTERVAL' is 250.  Is SPACING must be twice as INTERVAL?  I set SPACING twice as INTERVAL in my tests

**Comment by untergasser** [comment]
Hi, sequencing primers are not matched to each other, so the check if primers work with each other is missing. The article about Primer3 describes the spacing of primers in the task.

Currently you have to use the default task and move the targets over the sequence to get primers for nested PCR.

Best,
Andreas

**Comment by yangjw1996** [comment]
Thank you for your relpy and advice. It helps me a lot!

Best wishes!
jiawen
