### ISSUE TITLE
`max_loop` not working when calculating hairpin structure?

### ISSUE THREAD

**Issue by GuoYu-Peng** [primer3-org/primer3#73]
I reported this issue at primer3-py before, link: https://github.com/libnano/primer3-py/issues/107  
Can you fix this problem? Thanks.

**Comment by grinner** [comment]
This is an upstream `primer3` issue.  We may address this, but for now we will not.

**Comment by untergasser** [comment]
Why should we? If primers are picked, max_loop is working. If you check a single primer, the parameters are put out (check funktion). So handle the output as you like - try an if clause.

**Comment by GuoYu-Peng** [comment]
Ok, thanks.
