### ISSUE TITLE
Issue when make test

### ISSUE THREAD

**Issue by nanu4github** [primer3-org/primer3#75]
After I download the tar file and unpacked it and finally, I started `make all` and `make test`. I found the ` make all` code in /scr subfolder goes well but when I run `make test` it just throwed some errors in my screen, like `handling of too-long sequence...` `testing fatal errors...`. Most unfortunately there were some `FAILED` there. It advises me to check the test files, but I really do not know where the output files are and how to fix it. I will be really grateful if you answer the question.

**Comment by untergasser** [comment]
I am late - but without more information like platform and what you did it makes no sense.

Primer3 compiles without errors as you can see from the actions. You can compile it from source as described on this page.

Best,

Andreas
