### ISSUE TITLE
ntthal negative Tm calculations

### ISSUE THREAD

**Issue by cesimsek** [primer3-org/primer3#77]
Hi, 

I am using primer3-py, which is an python-abstracted API of primer3. 

I had the following issue with the homodimer calculations: https://github.com/libnano/primer3-py/issues/141

Briefly, the primer3 based (ntthal) command is as follows:

```
$ ./ntthal -mv 50 -dv 1.5 -n 0.6 -d 50 -s1 AGCTGCGTAATGACTAGGTA -s2 AGCTGCGTAATGACTAGGTA -path ./primer3_config/ 
Calculated thermodynamical parameters for dimer:	dS = -127.597	dH = -43000	dG = -3425.8	t = -10.5692
SEQ	AGCTGCGTAATGA    GTA----------
SEQ	             CTAG             
STR	             GATC             
STR	          ATG    AGTAATGCGTCGA
```

Which yielded a negative Tm for the predicted primer dimer. Cannot provide system info as this was based on the primer3-py tool, but in general what could be the reason for obtaining negative Tm?

Thanks!

**Comment by DougTownsend** [comment]
Melting temperature is calculated with the formula shown in the "Thermodynamics of the two-state model" section of this article https://en.wikipedia.org/wiki/Nucleic_acid_thermodynamics

Melting temperature is just the theoretical temperature at which, for a certain concentration of DNA, half of the DNA will be bound. A negative melting temperature just means that the secondary structure will only exist in very small concentrations at normal temperatures.

**Comment by untergasser** [comment]
Could not have explained it better.

Best,

Andreas
