### ISSUE TITLE
ntthal set defaults are different than ntthal usage information defaults

### ISSUE THREAD

**Issue by emmcauley** [primer3-org/primer3#79]
In primer3 release 2.6.1, I notice that the [ntthal usage information](https://github.com/primer3-org/primer3/blob/7f9f17d6012f404e83bbf0f931a4d06eb4af465b/src/thal_main.c#L90) provides a default of 0.0 mM for dNTP concentration:
~~~
usage = "USAGE: %s OPTIONS oligo\n"
     "-n  dNTP_conc        - concentration of deoxynycleotide triphosphate in mM, by default 0 mM\n"
     "\n"
~~~

However, when I check where the default parameters are actually set in `set_thal_default_args`, it looks like the default for dNTP concentration [is actually 0.8 mM](https://github.com/primer3-org/primer3/blob/7f9f17d6012f404e83bbf0f931a4d06eb4af465b/src/thal.c#L737). `set_thal_default_args` is called [on this line](https://github.com/primer3-org/primer3/blob/7f9f17d6012f404e83bbf0f931a4d06eb4af465b/src/thal_main.c#L74):
~~~
set_thal_default_args(thal_args *a)
{
   memset(a, 0, sizeof(*a));
   a->type = thal_any; /* thal_alignment_type THAL_ANY */
   a->maxLoop = MAX_LOOP;
   a->mv = 50; /* mM */
   a->dv = 0.0; /* mM */
   a->dntp = 0.8; /* mM */
   a->dna_conc = 50; /* nM */
   a->temp = TEMP_KELVIN; /* Kelvin */
   a->dimer = 1; /* by default dimer structure is calculated */
}
~~~

Happy to open a PR to change the usage information if that would be helpful. Thanks!

**Comment by untergasser** [comment]
Thank you for the bug report and the pull request. You are right, I just merged it.

Best,
Andreas
