### ISSUE TITLE
Wrong melting temperature in check_primer task

### ISSUE THREAD

**Issue by vzmisha4** [primer3-org/primer3#9]
When performing check_primers task via commandline I get completely wrong melting temperatures. Only noticed this now, and this is so unfortunate, because I've been using the tool for years. Below is an example: the actual melting temperature (according to online tools, such as the ThermoFisher primer check) is 68C, and here it says TM=59.738. Since the default parameters on the site are 57 to 62 this shouldn't even pass, supposedly.

SEQUENCE_ID=test123
PRIMER_TASK=check_primers
PRIMER_MIN_SIZE=18
PRIMER_MAX_SIZE=27
SEQUENCE_PRIMER=AGCGGTAGCCACGTTCTG
PRIMER_EXPLAIN_FLAG=1
PRIMER_LEFT_EXPLAIN=considered 1, ok 1
PRIMER_LEFT_NUM_RETURNED=1
PRIMER_TM_FORMULA=1
PRIMER_LEFT_EXPLAIN=considered 1, ok 1
PRIMER_LEFT_NUM_RETURNED=1
PRIMER_RIGHT_NUM_RETURNED=0
PRIMER_INTERNAL_NUM_RETURNED=0
PRIMER_PAIR_NUM_RETURNED=0
PRIMER_LEFT_0_PENALTY=2.261671
PRIMER_LEFT_0_SEQUENCE=AGCGGTAGCCACGTTCTG
PRIMER_LEFT_0=0,18
PRIMER_LEFT_0_TM=59.738
PRIMER_LEFT_0_GC_PERCENT=61.111
PRIMER_LEFT_0_SELF_ANY_TH=0.00
PRIMER_LEFT_0_SELF_END_TH=0.00
PRIMER_LEFT_0_HAIRPIN_TH=46.67
PRIMER_LEFT_0_END_STABILITY=3.0200

**Comment by vzmisha4** [comment]
Actually, same thing happens with the 'general' task as well. For instance, it suggests me here 'CGTTCTGATACTGGCTAGAAGC' as a left primer, and states TM as 58.623. You can easily check here (https://tmcalculator.neb.com/#!/main) or here (https://www.thermofisher.com/ru/ru/home/brands/thermo-scientific/molecular-biology/molecular-biology-learning-center/molecular-biology-resource-library/thermo-scientific-web-tools/multiple-primer-analyzer.html) that it is higher. Surprisingly, these sites also give a bit different results (65 and 62.3, respectively), so I am kind of confused as to what is right here.

SEQUENCE_ID=example
SEQUENCE_TEMPLATE=AGCGGTAGCCACGTTCTGATACTGGCTAGAAGCCAGGGGAGGGAGCTTGGGGTAAGGGGAGGGCCCTGAGGGAGGGGTCAGACGCTTTAGGAAAGAGTTAATGCGAAGAGGGGGAGGGGATAGGACGAAGAAACCGAAGGGAAAGCTCAGGGCCGCCAACTTCCAGCTGCAGCGGCGACTTTCAGTTTCATTTCCACGGACCCTCCTGCCTGGGCCGCAGCCGCCGCCGCGATGCCCAGTAAGTTCAGCTGCCGGCAGCTCCGGGAGGCGGGCCAGTGTTTCGAGAGTTTCCTGGTCGTT
SEQUENCE_TARGET=37,21
PRIMER_TASK=generic
PRIMER_PICK_LEFT_PRIMER=1
PRIMER_PICK_INTERNAL_OLIGO=1
PRIMER_PICK_RIGHT_PRIMER=1
PRIMER_OPT_SIZE=18
PRIMER_MIN_SIZE=15
PRIMER_MAX_SIZE=27
PRIMER_MAX_NS_ACCEPTED=1
PRIMER_PRODUCT_SIZE_RANGE=75-100
P3_FILE_FLAG=1
SEQUENCE_INTERNAL_EXCLUDED_REGION=37,21
PRIMER_EXPLAIN_FLAG=1
PRIMER_LEFT_EXPLAIN=considered 221, low tm 115, high tm 40, high hairpin stability 28, ok 38
PRIMER_RIGHT_EXPLAIN=considered 2814, GC content failed 335, low tm 653, high tm 1194, high any compl 6, high hairpin stability 70, ok 556
PRIMER_INTERNAL_EXPLAIN=considered 2353, overlap excluded region 47, GC content failed 251, low tm 828, high tm 482, high any compl 6, high hairpin stability 116, ok 623
PRIMER_PAIR_EXPLAIN=considered 20135, unacceptable product size 17511, no internal oligo 2619, ok 5
PRIMER_LEFT_NUM_RETURNED=5
PRIMER_RIGHT_NUM_RETURNED=5
PRIMER_INTERNAL_NUM_RETURNED=5
PRIMER_PAIR_NUM_RETURNED=5
PRIMER_PAIR_0_PENALTY=11.885202
PRIMER_LEFT_0_PENALTY=5.376540
PRIMER_RIGHT_0_PENALTY=6.508662
PRIMER_INTERNAL_0_PENALTY=1.312503
PRIMER_LEFT_0_SEQUENCE=CGTTCTGATACTGGCTAGAAGC
PRIMER_RIGHT_0_SEQUENCE=CCTCTTCGCATTAACTCTTTCCT
PRIMER_INTERNAL_0_SEQUENCE=CCTGAGGGAGGGGTCAGACGC
PRIMER_LEFT_0=11,22
PRIMER_RIGHT_0=110,23
PRIMER_INTERNAL_0=64,21
PRIMER_LEFT_0_TM=58.623
PRIMER_RIGHT_0_TM=58.491
PRIMER_INTERNAL_0_TM=60.313
PRIMER_LEFT_0_GC_PERCENT=50.000
PRIMER_RIGHT_0_GC_PERCENT=43.478
PRIMER_INTERNAL_0_GC_PERCENT=71.429
PRIMER_INTERNAL_0_SELF_ANY_TH=5.42
PRIMER_LEFT_0_SELF_ANY_TH=3.17
PRIMER_RIGHT_0_SELF_ANY_TH=0.00
PRIMER_INTERNAL_0_SELF_END_TH=5.42
PRIMER_LEFT_0_SELF_END_TH=0.00
PRIMER_RIGHT_0_SELF_END_TH=0.00
PRIMER_LEFT_0_HAIRPIN_TH=41.46
PRIMER_RIGHT_0_HAIRPIN_TH=0.00
PRIMER_INTERNAL_0_HAIRPIN_TH=37.85
PRIMER_LEFT_0_END_STABILITY=3.8600
PRIMER_RIGHT_0_END_STABILITY=3.3600
PRIMER_PAIR_0_COMPL_ANY_TH=0.00
PRIMER_PAIR_0_COMPL_END_TH=0.00
PRIMER_PAIR_0_PRODUCT_SIZE=100
PRIMER_PAIR_1_PENALTY=12.243222
PRIMER_LEFT_1_PENALTY=5.376540
PRIMER_RIGHT_1_PENALTY=6.866682
PRIMER_INTERNAL_1_PENALTY=1.312503
PRIMER_LEFT_1_SEQUENCE=CGTTCTGATACTGGCTAGAAGC
PRIMER_RIGHT_1_SEQUENCE=CCTCTTCGCATTAACTCTTTCC
PRIMER_INTERNAL_1_SEQUENCE=CCTGAGGGAGGGGTCAGACGC
PRIMER_LEFT_1=11,22
PRIMER_RIGHT_1=110,22
PRIMER_INTERNAL_1=64,21
PRIMER_LEFT_1_TM=58.623
PRIMER_RIGHT_1_TM=57.133
PRIMER_INTERNAL_1_TM=60.313
PRIMER_LEFT_1_GC_PERCENT=50.000
PRIMER_RIGHT_1_GC_PERCENT=45.455
PRIMER_INTERNAL_1_GC_PERCENT=71.429
PRIMER_INTERNAL_1_SELF_ANY_TH=5.42
PRIMER_LEFT_1_SELF_ANY_TH=3.17
PRIMER_RIGHT_1_SELF_ANY_TH=0.00
PRIMER_INTERNAL_1_SELF_END_TH=5.42
PRIMER_LEFT_1_SELF_END_TH=0.00
PRIMER_RIGHT_1_SELF_END_TH=0.00
PRIMER_LEFT_1_HAIRPIN_TH=41.46
PRIMER_RIGHT_1_HAIRPIN_TH=0.00
PRIMER_INTERNAL_1_HAIRPIN_TH=37.85
PRIMER_LEFT_1_END_STABILITY=3.8600
PRIMER_RIGHT_1_END_STABILITY=3.1300
PRIMER_PAIR_1_COMPL_ANY_TH=0.00
PRIMER_PAIR_1_COMPL_END_TH=0.00
PRIMER_PAIR_1_PRODUCT_SIZE=100
PRIMER_PAIR_2_PENALTY=13.037997
PRIMER_LEFT_2_PENALTY=5.376540
PRIMER_RIGHT_2_PENALTY=7.661458
PRIMER_INTERNAL_2_PENALTY=1.312503
PRIMER_LEFT_2_SEQUENCE=CGTTCTGATACTGGCTAGAAGC
PRIMER_RIGHT_2_SEQUENCE=CCTCTTCGCATTAACTCTTTCCTA
PRIMER_INTERNAL_2_SEQUENCE=CCTGAGGGAGGGGTCAGACGC
PRIMER_LEFT_2=11,22
PRIMER_RIGHT_2=110,24
PRIMER_INTERNAL_2=64,21
PRIMER_LEFT_2_TM=58.623
PRIMER_RIGHT_2_TM=58.339
PRIMER_INTERNAL_2_TM=60.313
PRIMER_LEFT_2_GC_PERCENT=50.000
PRIMER_RIGHT_2_GC_PERCENT=41.667
PRIMER_INTERNAL_2_GC_PERCENT=71.429
PRIMER_INTERNAL_2_SELF_ANY_TH=5.42
PRIMER_LEFT_2_SELF_ANY_TH=3.17
PRIMER_RIGHT_2_SELF_ANY_TH=0.00
PRIMER_INTERNAL_2_SELF_END_TH=5.42
PRIMER_LEFT_2_SELF_END_TH=0.00
PRIMER_RIGHT_2_SELF_END_TH=0.00
PRIMER_LEFT_2_HAIRPIN_TH=41.46
PRIMER_RIGHT_2_HAIRPIN_TH=0.00
PRIMER_INTERNAL_2_HAIRPIN_TH=37.85
PRIMER_LEFT_2_END_STABILITY=3.8600
PRIMER_RIGHT_2_END_STABILITY=2.9400
PRIMER_PAIR_2_COMPL_ANY_TH=0.00
PRIMER_PAIR_2_COMPL_END_TH=0.00
PRIMER_PAIR_2_PRODUCT_SIZE=100
PRIMER_PAIR_3_PENALTY=13.483212
PRIMER_LEFT_3_PENALTY=5.376540
PRIMER_RIGHT_3_PENALTY=8.106673
PRIMER_INTERNAL_3_PENALTY=1.312503
PRIMER_LEFT_3_SEQUENCE=CGTTCTGATACTGGCTAGAAGC
PRIMER_RIGHT_3_SEQUENCE=CCTCTTCGCATTAACTCTTTCCTAA
PRIMER_INTERNAL_3_SEQUENCE=CCTGAGGGAGGGGTCAGACGC
PRIMER_LEFT_3=11,22
PRIMER_RIGHT_3=110,25
PRIMER_INTERNAL_3=64,21
PRIMER_LEFT_3_TM=58.623
PRIMER_RIGHT_3_TM=58.893
PRIMER_INTERNAL_3_TM=60.313
PRIMER_LEFT_3_GC_PERCENT=50.000
PRIMER_RIGHT_3_GC_PERCENT=40.000
PRIMER_INTERNAL_3_GC_PERCENT=71.429
PRIMER_INTERNAL_3_SELF_ANY_TH=5.42
PRIMER_LEFT_3_SELF_ANY_TH=3.17
PRIMER_RIGHT_3_SELF_ANY_TH=0.00
PRIMER_INTERNAL_3_SELF_END_TH=5.42
PRIMER_LEFT_3_SELF_END_TH=0.00
PRIMER_RIGHT_3_SELF_END_TH=0.00
PRIMER_LEFT_3_HAIRPIN_TH=41.46
PRIMER_RIGHT_3_HAIRPIN_TH=0.00
PRIMER_INTERNAL_3_HAIRPIN_TH=37.85
PRIMER_LEFT_3_END_STABILITY=3.8600
PRIMER_RIGHT_3_END_STABILITY=2.6900
PRIMER_PAIR_3_COMPL_ANY_TH=0.00
PRIMER_PAIR_3_COMPL_END_TH=0.00
PRIMER_PAIR_3_PRODUCT_SIZE=100
PRIMER_PAIR_4_PENALTY=13.970698
PRIMER_LEFT_4_PENALTY=5.376540
PRIMER_RIGHT_4_PENALTY=8.594159
PRIMER_INTERNAL_4_PENALTY=1.312503
PRIMER_LEFT_4_SEQUENCE=CGTTCTGATACTGGCTAGAAGC
PRIMER_RIGHT_4_SEQUENCE=CCTCTTCGCATTAACTCTTTCCTAAA
PRIMER_INTERNAL_4_SEQUENCE=CCTGAGGGAGGGGTCAGACGC
PRIMER_LEFT_4=11,22
PRIMER_RIGHT_4=110,26
PRIMER_INTERNAL_4=64,21
PRIMER_LEFT_4_TM=58.623
PRIMER_RIGHT_4_TM=59.406
PRIMER_INTERNAL_4_TM=60.313
PRIMER_LEFT_4_GC_PERCENT=50.000
PRIMER_RIGHT_4_GC_PERCENT=38.462
PRIMER_INTERNAL_4_GC_PERCENT=71.429
PRIMER_INTERNAL_4_SELF_ANY_TH=5.42
PRIMER_LEFT_4_SELF_ANY_TH=3.17
PRIMER_RIGHT_4_SELF_ANY_TH=0.00
PRIMER_INTERNAL_4_SELF_END_TH=5.42
PRIMER_LEFT_4_SELF_END_TH=0.00
PRIMER_RIGHT_4_SELF_END_TH=0.00
PRIMER_LEFT_4_HAIRPIN_TH=41.46
PRIMER_RIGHT_4_HAIRPIN_TH=0.00
PRIMER_INTERNAL_4_HAIRPIN_TH=37.85
PRIMER_LEFT_4_END_STABILITY=3.8600
PRIMER_RIGHT_4_END_STABILITY=1.8500
PRIMER_PAIR_4_COMPL_ANY_TH=0.00
PRIMER_PAIR_4_COMPL_END_TH=0.00
PRIMER_PAIR_4_PRODUCT_SIZE=100
=

**Comment by untergasser** [comment]
Actually Tm calculation is not trivial and several methods exist. Primer3 uses the up to date nearest neighbor method with current parameters and calculates accurate results. Be aware that kation-, anion-, primer-, and dNTP-concentrations have an impact on the calculation. Other tools with other methods and other parameters may calculate something else and give you different results. Concerning Tm calculation, Primer3 is optimal to current knowledge.
